### ISSUE TITLE
Display run metrics on comparison page (when judgments are available)

### ISSUE THREAD

**Issue by andrewyates** [capreolus-ir/diffir#6]
Right now we only display the measure's value, so the difference in a metric is only displayed when the metric is also used as the measure of query difference. It would be nice to always display metrics when we have them.

**Comment by thongnt99** [comment]
Which metrics should we show in the case where metric is not used as the measure of difference?

**Comment by andrewyates** [comment]
maybe P and nDCG at 1,3,5,10?
